set -sg escape-time 0
set -g base-index 1
set -g mode-keys vi

# Renumber windows on window close
set -g renumber-windows on

# Told to set this by nvim :checkhealth to enable `focus-events`
set-option -g focus-events on
# Told to set this by nvim :checkhealth to allow 'termguicolors' to work properly
# This doesn't seem to work, but it's not breaking anything, so I'll leave it here for now
set-option -a terminal-features 'tmux-256color:RGB'
