add_newline = false
command_timeout = 200
format = '''
┏\[$username$hostname\]-\[$directory\]$git_branch-\[$time\]
┗\[$status\] '''

[hostname]
style = 'cyan'
format = ' [$hostname]($style)'

[username]
show_always = true
format = '[$user]($style)'

[time]
format = '[$time]($style)'
style = 'bright-black'
disabled = false

[status]
symbol = '$status'
failure_style = 'bold red'
success_symbol = '$status'
success_style = 'bold green'
recognize_signal_code = false
format = '[$status]($style)'
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "^/"
format = '[$path]($style)'
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)"

[git_branch]
format = '-\[[$branch]($style)\]'
style = "italic cyan"

# [git_status]
# format     = '-\[[$all_status]($style)\]'
# style      = "cyan"
# ahead      = "⇡${count} "
# diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
# behind     = "⇣${count} "
# conflicted = " "
# up_to_date = " "
# untracked  = "? "
# modified   = " "
# stashed    = ""
# staged     = ""
# renamed    = ""
# deleted    = ""
